import "./globals.css";
export const metadata = {
  title: "Tarea modulo 4 unidad 1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
