import "@/estilos/globals.css"
import Nav from "@/componentes/nav";



export const metadata = {
  title: "Recetas de cocteles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
         <header>
          <div className="holder">
            <div className="logo">
              <img src="/imagenes/logo coctel chico.jpg" width="100" alt="logo cocteleria" />
              <h1>Recetas de cocteleria</h1>
            </div>
          </div>
        </header>
        <Nav/> 
        {children}
          <footer>Diseñado por Camila Calabrese 2025</footer>
      </body>
    </html>
  );
}
